### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'obj'

### ISSUE THREAD

**Issue by chrisinmtown** [py-pdf/PyPDF2#164] opened 2014-12-18 16:12 UTC
PyPDF2 version 1.23 throws an invalid-literal exception when reading this file:

```
http://emma.msrb.org/EA502499-EA391023-EA787916.pdf
```

Here's the traceback, it blows up when reading the header:

```
Processing file EA502499-EA391023-EA787916.pdf
Traceback (most recent call last):
  File "show_pdf_props.py", line 27, in <module>
    show_pdf_props(sys.argv[1])
  File "show_pdf_props.py", line 14, in show_pdf_props
    pdf_obj = PdfFileReader(pdf_file)
  File "/Library/Python/2.7/site-packages/PyPDF2/pdf.py", line 913, in **init**
    self.read(stream)
  File "/Library/Python/2.7/site-packages/PyPDF2/pdf.py", line 1570, in read
    idnum, generation = self.readObjectHeader(stream)
  File "/Library/Python/2.7/site-packages/PyPDF2/pdf.py", line 1434, in readObjectHeader
    return int(idnum), int(generation)
ValueError: invalid literal for int() with base 10: 'obj'
```

I put a breakpoint and the debugger on that line, which revealed that as read from the file mentioned above, the variable 'generation' has the string value 'obj', which int() declines to convert to a number.

Just to be complete I'll attach my trivial script below.  Thanks for listening, PyPDF2 is a big help, hope this can be fixed easily.

```python
'''
Trivial script that shows PDF file properties.
Requires PyPDF2 from https://pypi.python.org/pypi/PyPDF2
'''

from __future__ import print_function
from PyPDF2 import PdfFileReader
import sys

def show_pdf_props(filename):
    # If the document is encrypted, the text length can't be fetched.
    print("Processing file %s" % filename)
    with open(filename, "rb") as pdf_file:
        pdf_obj = PdfFileReader(pdf_file)
        prop_en = pdf_obj.getIsEncrypted()
        if prop_en:
            print("File is encrypted, we're done here.")
        else:
            print("Page count: %d" % pdf_obj.getNumPages())
            print("Page 1 text length is %d" % len(pdf_obj.getPage(0).extractText()))
            docinfo = pdf_obj.getDocumentInfo()
            for key in docinfo: 
                print("Key %s, Value %s" % (key, docinfo[key]))

# Pass all params after program name to our main
if __name__ == "__main__":
    show_pdf_props(sys.argv[1])
```

**Comment by fgeek** [comment] 2015-03-07 21:49
Issue #183 might be duplicate with this one.

**Comment by abhinavnair** [comment] 2017-10-04 08:20
Hi, This happens to me with PDF files exported from Google Docs, Sheets. I don't think the PDF is malformed.

**Comment by sorter** [comment] 2017-11-13 19:23
This is also occurring for me on PDF documents generated from FedEx. The PDF is certainly not malformed or else Google Chrome, Preview.app (on Mac) as well as Safari have no problem rendering them.

**Comment by patroqueeet** [comment] 2019-03-27 08:09
I had the exact same error from a pdf generated with `xhtml2pdf` python lib with merging files. Under python2.7 this combination of:

* generate PDF with xhtml2pdf and
* merge files together with PyPDF2

worked fine. But after upgrade to Python 3.7 the above error showed up. I debugged the code and found the following solution, but it might be not proper for other users. Still I like to share it.

Assumption: the method `readUntilWhitespace` is used only in two places. Both are looking for `int`values. Hence this ugly monkey patch works well for me:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
""" we don't want that """

from PyPDF2 import pdf


def stableReadUntilWhitespace(stream, maxchars=None):
    """
    Reads non-whitespace characters and returns them.
    Stops upon encountering whitespace or when maxchars is reached.
    """
    txt = b""
    while True:
        tok = stream.read(1)
        if txt and tok.isspace() or not tok:
            break
        # must be int
        try:
            int(tok)
        except ValueError:
            continue
        txt += tok
        if len(txt) == maxchars:
            break
    return txt


pdf.readUntilWhitespace = stableReadUntilWhitespace
```

**Comment by entargo** [comment] 2021-03-04 19:21
Putting the range in a list solved the problem for me. Here is the stackoverflow explanation https://stackoverflow.com/questions/94935/what-is-the-difference-between-range-and-xrange-functions-in-python-2-x

for page in list(range(pdf.getNumPages())):

**Comment by lambdaTotoro** [comment] 2021-06-28 17:52
This might be an ugly solution, monkey-patching a library function like that, but it solved my problem.
This should be in a release.

**Comment by MartinThoma** [comment] 2022-04-16 11:50
@patroqueeet or @lambdaTotoro : Do you want to make a PR?

**Comment by lambdaTotoro** [comment] 2022-04-26 11:54
@MartinThoma Sure, here you go!

**Comment by MartinThoma** [comment] 2022-07-09 14:20
This is the PR: https://github.com/py-pdf/PyPDF2/pull/824

**Comment by MartinThoma** [comment] 2022-07-24 07:19
The PDF to check the issue is no longer available. I cannot verify if the problem still exists / if the proposed solutions solve it.

If anybody encounters this issue again, please share the PDF / the code that caused it.

For the moment, I will close this issue and #1160 and #824.

Thank you all for your work :heart: I realize that it's disappointing that no code change was done after this, but I fear that this fix might break other things. Without clear evidence that the problem still exists, I will not risk it.

**Closed by MartinThoma** 2022-07-24 07:19 UTC
Labels: is-bug, needs-pdf
