### ISSUE TITLE
Error when reading PDF file using PdfReader

### ISSUE THREAD

**Issue by aanctilAD** [py-pdf/PyPDF2#1205] opened 2022-08-05 14:07 UTC
When Reading a specific PDF document using PdfFileReader I encounter the issue:

`Invalid stream (index 99) within object 8870 0: Stream has ended unexpectedly`

Adding the strict argument to the PdfFileReader function allows the code to continue running but the error still occurs

`PdfReader(pdf_path, strict = False)`

I would like to find a fix to the issue so that I do not have to use `strict = False` as a temporary fix.
## Environment

```bash
$ python -m platform
Linux-4.14.252-131.483.amzn1.x86_64-x86_64-with-glibc2.10

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.9.0
```

## Code 

Line of Code that causes the issue.

```python
from PyPDF2 import PdfReader

doc_orig = PdfReader(pdf_path)
```

Due to security reasons, I am unable to share the PDF document that is causing this issue.

## Traceback

This is the complete Traceback I see:

```
Invalid stream (index 99) within object 8870 0: Stream has ended unexpectedly

---------------------------------------------------------------------------
PdfStreamError                            Traceback (most recent call last)
File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_reader.py:1090, in PdfReader._get_object_from_stream(self, indirect_reference)
   1089 try:
-> 1090     obj = read_object(stream_data, self)
   1091 except PdfStreamError as exc:
   1092     # Stream object cannot be read. Normally, a critical error, but
   1093     # Adobe Reader doesn't complain, so continue (in strict mode?)

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/generic.py:1366, in read_object(stream, pdf, forced_encoding)
   1365 else:
-> 1366     return NumberObject.read_from_stream(stream)

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/generic.py:385, in NumberObject.read_from_stream(stream)
    383 @staticmethod
    384 def read_from_stream(stream: StreamType) -> Union["NumberObject", FloatObject]:
--> 385     num = read_until_regex(stream, NumberObject.NumberPattern)
    386     if num.find(b".") != -1:

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_utils.py:158, in read_until_regex(stream, regex, ignore_eof)
    157         return name
--> 158     raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
    159 m = regex.search(tok)

PdfStreamError: Stream has ended unexpectedly

During handling of the above exception, another exception occurred:

PdfReadError                              Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 add_bookmarks_to_pdf('/home/ec2-user/SageMaker/BL-154REP.pdf',[{'text':'foo','page':2}],[],'/home/ec2-user/SageMaker/test.pdf')

File ~/SageMaker/pyarmordoc/pyarmordoc/bookmarking/bookmarking.py:78, in add_bookmarks_to_pdf(pdf_path, bookmarks, rotations, save_path)
     74     logger.error(f'Failed to save {save_path}.')
     76     logger.exception(e)
---> 78     raise e
     80 logger.info(f'{save_path} bookmarked.')

File ~/SageMaker/pyarmordoc/pyarmordoc/bookmarking/bookmarking.py:71, in add_bookmarks_to_pdf(pdf_path, bookmarks, rotations, save_path)
     69 try:
     70     with open(save_path, 'wb') as f:
---> 71         doc_new.write(f)
     73 except Exception as e:
     74     logger.error(f'Failed to save {save_path}.')

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_writer.py:799, in PdfWriter.write(self, stream)
    789     self._root = self._add_object(self._root_object)
    791 # PDF objects sometimes have circular references to their /Page objects
    792 # inside their object tree (for example, annotations).  Those will be
    793 # indirect references to objects that we've recreated in this PDF.  To
   (...)
    797 # trees to reference the correct new object location, rather than
    798 # copying in a new copy of the page object.
--> 799 self._sweep_indirect_references(self._root)
    801 object_positions = self._write_header(stream)
    802 xref_location = self._write_xref_table(stream, object_positions)

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_writer.py:921, in PdfWriter._sweep_indirect_references(self, root)
    912         stack.append(
    913             (
    914                 value,
   (...)
    918             )
    919         )
    920 elif isinstance(data, IndirectObject):
--> 921     data = self._resolve_indirect_object(data)
    923     if str(data) not in discovered:
    924         discovered.append(str(data))

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_writer.py:966, in PdfWriter._resolve_indirect_object(self, data)
    963     raise ValueError(f"I/O operation on closed file: {data.pdf.stream.name}")
    965 # Get real object indirect object
--> 966 real_obj = data.pdf.get_object(data)
    968 if real_obj is None:
    969     logger_warning(
    970         f"Unable to resolve [{data.__class__.__name__}: {data}], "
    971         "returning NullObject instead",
    972         __name__,
    973     )

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_reader.py:1121, in PdfReader.get_object(self, indirect_reference)
   1116     return retval
   1117 if (
   1118     indirect_reference.generation == 0
   1119     and indirect_reference.idnum in self.xref_objStm
   1120 ):
-> 1121     retval = self._get_object_from_stream(indirect_reference)  # type: ignore
   1122 elif (
   1123     indirect_reference.generation in self.xref
   1124     and indirect_reference.idnum in self.xref[indirect_reference.generation]
   1125 ):
   1126     if self.xref_free_entry.get(indirect_reference.generation, {}).get(
   1127         indirect_reference.idnum, False
   1128     ):

File ~/anaconda3/envs/py38/lib/python3.8/site-packages/PyPDF2/_reader.py:1102, in PdfReader._get_object_from_stream(self, indirect_reference)
   1094 logger_warning(
   1095     f"Invalid stream (index {i}) within object "
   1096     f"{indirect_reference.idnum} {indirect_reference.generation}: "
   1097     f"{exc}",
   1098     __name__,
   1099 )
   1101 if self.strict:
-> 1102     raise PdfReadError(f"Can't read object stream: {exc}")
   1103 # Replace with null. Hopefully it's nothing important.
   1104 obj = NullObject()

PdfReadError: Can't read object stream: Stream has ended unexpectedly
```

**Comment by MartinThoma** [comment] 2022-08-05 18:22
Is it possible to open the file with PDF viewers (e.g. Google Chrome / Adobe Reader)?

Are other packages (e.g. [tika](https://pypi.org/project/tika/) / [Pdfium](https://pypi.org/project/pypdfium2/) / [PyMuPDF](https://pypi.org/project/PyMuPDF/)) able to extract the text?

**Comment by aanctilAD** [comment] 2022-08-05 19:31
Yes, I am able to open the PDF document in different PDF viewers. I am also able to extract the text using other packages.

**Comment by MartinThoma** [comment] 2022-08-05 19:38
@aanctilAD Have you tried `strict=False` for the `PdfReader`?

**Comment by MartinThoma** [comment] 2022-08-06 06:23
> I would like to find a fix to the issue so that I do not have to use strict = False as a temporary fix.

This is not a bug in PyPDF2, but the PDF file does not conform to the PDF standard. PyPDF2 can work around it - and it does so, if `strict=False` is set. See https://pypdf2.readthedocs.io/en/latest/user/robustness.html

I'm closing this, as everything seems to go as expected.

**Closed by MartinThoma** 2022-08-06 06:23 UTC
Labels: PdfReader, is-robustness-issue, needs-pdf
