### ISSUE TITLE
Debian bug reports 1010820 & 1010821: autopkgtest issues

### ISSUE THREAD

**Issue by akrabat** [py-pdf/PyPDF2#895] opened 2022-05-24 10:15 UTC
I don't know this is directly a PyPDF2 issue but Debian bugs [101020](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010820) & [1010821](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010821) means that pypdf2 is slated to be removed from Debian.

> With a recent upload of pypdf2 the autopkgtest of bookletimposer fails 
> in testing when that autopkgtest is run with the binary packages of 
> pypdf2 from unstable. It passes when run with only packages from 
> testing.

and

> With a recent upload of pypdf2 the autopkgtest of xml2rfc fails in 
> testing when that autopkgtest is run with the binary packages of pypdf2 
> from unstable. It passes when run with only packages from testing. 

> Currently this regression is blocking the migration of pypdf2 to testing 
> [1]. Due to the nature of this issue, I filed this bug report against 
> both packages. Can you please investigate the situation and reassign the 
> bug to the right package?

**Comment by akrabat** [comment] 2022-05-24 10:16
For context, I'm a maintainer for rst2pdf and received this email:


> rst2pdf 0.98-2 is marked for autoremoval from testing on 2022-06-23
> 
> It (build-)depends on packages with these RC bugs:
> 1010820: pypdf2, src:bookletimposer: pypdf2 breaks bookletimposer autopkgtest: Can't get Fields array
> https://bugs.debian.org/1010820
> 1010821: pypdf2, src:xml2rfc: pypdf2 breaks xml2rfc autopkgtest: lxml.etree.XMLSyntaxError: PCDATA invalid Char value 1
> https://bugs.debian.org/1010821

**Comment by MartinThoma** [comment] 2022-05-24 18:07
Thank you for letting us know!

This is booletimposer: http://manpages.ubuntu.com/manpages/bionic/man1/bookletimposer.1.html (had to look it up)

The error message is:

```
autopkgtest [04:57:01]: test integration: [-----------------------
0%: creating page 1
50%: creating page 2
100%: writing converted file
100%: done
Syntax Error: Can't get Fields array<0a>
1
Syntax Error: Can't get Fields array<0a>
1
0%: extracting page 1
25%: extracting page 2
50%: extracting page 3
75%: extracting page 4
100%: writing converted file
100%: done
Syntax Error: Can't get Fields array<0a>
1
Syntax Error: Can't get Fields array<0a>
1
1
autopkgtest [04:57:02]: test integration: -----------------------]
autopkgtest [04:57:02]: test integration:  - - - - - - - - - - results - - - - - - - - - -
integration          FAIL stderr: Syntax Error: Can't get Fields array<0a>
autopkgtest [04:57:02]: test integration:  - - - - - - - - - - stderr - - - - - - - - - -
Syntax Error: Can't get Fields array<0a>
Syntax Error: Can't get Fields array<0a>
Syntax Error: Can't get Fields array<0a>
Syntax Error: Can't get Fields array<0a>
autopkgtest [04:57:02]: @@@@@@@@@@@@@@@@@@@@ summary
unittests            PASS
integration          FAIL stderr: Syntax Error: Can't get Fields array<0a>
```

I have no clue where this comes from.

**Comment by MartinThoma** [comment] 2022-05-24 18:08
The other message is:

```
Traceback (most recent call last):
  File 
"/tmp/autopkgtest-lxc.mlxdmdjo/downtmp/build.EDj/src/xxx/test.py", line 
495, in setUpClass
    cls.elements_pdfxml = xmldoc(None, bytes=elements_pdfdoc)
  File "/usr/lib/python3/dist-packages/xml2rfc/walkpdf.py", line 97, in 
xmldoc
    return lxml.etree.fromstring(text)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in 
lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in 
lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 11931
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 1, line 11931, column 5
```

**Comment by MartinThoma** [comment] 2022-05-24 18:13
I've contacted 	kjo from bookletimposer and hope they will help us understand where the issue is.

**Comment by MartinThoma** [comment] 2022-07-09 13:46
I don't receive a response. I close this issue now as I cannot see a PyPDF2 issue.

**Closed by MartinThoma** 2022-07-09 13:46 UTC
Labels: is-bug
