### ISSUE TITLE
pyPDF2 can crash python when another module tries to raise a warning

### ISSUE THREAD

**Issue by TinBane** [py-pdf/PyPDF2#1308] opened 2022-08-31 06:24 UTC
We are using PyPDF2 in a web application running on uwsgi/falcon. And we started getting random crashes in locations that were not using PyPDF2, whenever falcon attempted to raise a deprecation warning.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.5.1-arm64-arm-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
1.26.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
Run a framework (like falcon) as a uwsgi app, and import PyPDF2.
Have any library try and raise a warning
PyPDF2 has overridden the warning, and assumes a length >= 2 for the split it does to extract the second element.
In an environment similar to mine, the filename has no slashes, so it is a length 1 array, and you get an index error.

Suggested solution:
Either pull the last value (if that's what you want?) or at least try/except and fall back to including the full filename path.

At PyPDF2/utils.py", line 69
Replace:
file = filename.replace("/", "\\").rsplit("\\", 1)[1]
With:
file = filename.replace("/", "\\").rsplit("\\", 1)[-1]
OR
try:
    file = filename.replace("/", "\\").rsplit("\\", 1)[1]
except:
    file = filename
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/falcon/app.py", line 361, in __call__
    responder(req, resp, **params)
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/newrelic/hooks/framework_falcon.py", line 65, in method_wrapper
    return wrapped(*args, **kwargs)
  File "sovereign.py", line 9370, in on_get
    resp.body = results.read()
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/falcon/util/deprecation.py", line 62, in wrapper
    warnings.warn(message, category=DeprecatedWarning, stacklevel=2)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/PyPDF2/pdf.py", line 1069, in _showwarning
    file.write(formatWarning(message, category, filename, lineno, line))
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/PyPDF2/utils.py", line 69, in formatWarning
    file = filename.replace("/", "\\").rsplit("\\", 1)[1] # find the file name
IndexError: list index out of range
```

As you can see, the stack goes from falcon which calls our app, to our app, to falcon's deprecation warning, to python's warning framework, to PyPDF2's code.
```
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/falcon/app.py", line 361
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/newrelic/hooks/framework_falcon.py", line 65
  File "sovereign.py", line 9370
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/falcon/util/deprecation.py", line 62
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/warnings.py", line 109
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/PyPDF2/pdf.py", line 1069
  File "/Users/user/Envs/Project3-UZGwIdNk/lib/python3.9/site-packages/PyPDF2/utils.py", line 69
```

**Comment by ediamondscience** [comment] 2022-08-31 06:43
It looks like you're using a version of PyPDF2 from May 2016. The current release is 2.10.4.

Please run 
`$ pip install PyPDF2 -U`
And see if the problem persists.

**Comment by MartinThoma** [comment] 2022-08-31 07:59
I'm pretty certain the issue is gone in a new version. The reason for the crash is likely that PyPDF2 modified how the warnings module works. We don't do that anymore since ~Mai 2022.

I'm closing this as the version is outdated. If you still see this issue with PyPDF2>=2.0.0, I can re-open the issue.

**Closed by MartinThoma** 2022-08-31 07:59 UTC
