### ISSUE TITLE
PyPDF2.utils.PdfReadError: EOF marker not found

### ISSUE THREAD

**Issue by umapathireddy** [py-pdf/PyPDF2#480] opened 2019-01-17 06:06 UTC
+ python /jenkinsdata/apihub/quality_scan/apihub_apicontent/workspace/Fortify/Fortify.py **** 11166 
Report Generation Successful
Report Downloaded for Project Id: 11166 & Project Name: 
Report Download Auth Code and Report Id: {'mat': 'YzBkNTU1M2EtOGFmNy00NTU5LThiYTAtNzlmMDdkNThiODRj', 'id': 22620}
Report Download Successful
Traceback (most recent call last):
  File "/jenkinsdata/apihub/quality_scan/apihub_apicontent/workspace/Fortify/Fortify.py", line 114, in <module>
    readReport()
  File "/jenkinsdata/apihub/quality_scan/apihub_apicontent/workspace/Fortify/Fortify.py", line 101, in readReport
    pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
  File "/var/jenkins_home/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/var/jenkins_home/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1696, in read
    raise utils.PdfReadError("EOF marker not found")
PyPDF2.utils.PdfReadError: EOF marker not found

**Comment by markdoliner** [comment] 2020-04-03 18:02
This may be a duplicate of https://github.com/mstamy2/PyPDF2/issues/177

I've seen this happen with a PDF that had more than 1024 extra bytes (comments or null bytes or some such) after the last %%EOF. My solution was to find the last %%EOF in the file and truncate everything after it (and if there is no %%EOF at all then append one).

@reportgunner I'm not super familiar with the PDF file format, but it may not be safe to remove or move `%%EOF` from other places in the file. I think that string may be used multiple times within the file to indicate the end of some sort of "block," not just the end of the entire file.

**Comment by MartinThoma** [comment] 2022-04-11 05:39
https://github.com/py-pdf/PyPDF2/issues/442 - let's close this issue and keep track of it in the other one

**Closed by MartinThoma** 2022-04-11 05:39 UTC
Labels: Bug
