### ISSUE TITLE
PyPDF2 hangs in NumberObject.NumberPattern.search as called by extractText()

### ISSUE THREAD

**Issue by chrisinmtown** [py-pdf/PyPDF2#180] opened 2015-02-16 02:05 UTC
Please download and try getting text from this doc using PyPDF2 version 1.23:

```
http://emma.msrb.org/EP713514-EP554286-EP955449.pdf
```

When I try it simply hangs forever in NumberObject.NumberPattern.search() invocation, as called by the extractText() function. This file is searchable text (not images) and not encrypted; about 5MB and 15 pages.  Partial traceback (omitting my code) is below.

Hope this is enough information, glad to provide more, thanks for your time. 
## 

  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 2352, in extractText
    content = ContentStream(content, self.pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 2425, in **init**
    data += s.getObject().getData()
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 174, in getObject
    return self.pdf.getObject(self).getObject()
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1378, in getObject
    retval = readObject(self.stream, self)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 63, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 599, in readFromStream
    length = pdf.getObject(length)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1360, in getObject
    retval = self._getObjectFromStream(indirectReference)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1333, in _getObjectFromStream
    obj = readObject(streamData, self)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 95, in readObject
    return NumberObject.readFromStream(stream)
  File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 259, in readFromStream
    m = NumberObject.NumberPattern.search(tok)

**Comment by MartinThoma** [comment] 2022-04-22 15:04
The file is no longer accessible. Do you have an example file that still is accessible?

**Comment by MartinThoma** [comment] 2022-06-06 12:59
I'm closing this issue as I cannot reproduce it.

**Closed by MartinThoma** 2022-06-06 12:59 UTC
Labels: Bug, Text Extraction, change-requested
