### ISSUE TITLE
PyPDF2 outputting ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by lnoah995** [py-pdf/PyPDF2#1246] opened 2022-08-17 05:57 UTC
Hello, I'm out of town and decided to install some packages I'd been using on my desktop onto my laptop. I installed PyPDF2 and started to encounter an error that I had not run into on my desktop. The error is as mentioned in the title. I'm creating a gui with Tkinter and the errors comes up when I try to fill some pdf checkboxes. I'm running the same program as I had on my desktop as well.

## Environment

Which environment were you using when you encountered the problem?
Anaconda Spyder

```
$ python -m platform
# TODO: Windows-10-10.0.19041-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
# TODO: 2.10.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```
for i in range(len(page["/Annots"])): #in order to access the "Annots" key 
        # print ((page["/Annots"][i].get_object())) #to find out which of the form fills are checkbox or text fill
        if (page["/Annots"][i].get_object())['/FT']=="/Btn" and (page["/Annots"][i].get_object())['/T']==flag: #this is my filter so that I can filter checkboxes and the checkbox I want i.e. "Check Box 3"
            # print (page["/Annots"][i].get_object()) #further check if I got what I wanted as per the filter
            writer_annot = page["/Annots"][i].get_object() 
            writer_annot.update(
            {
                NameObject("/V"): NameObject("/Yes"), #NameObject being only for checkbox, and please try "/Yes" or "/1" or "/On" to see which works
                NameObject("/AS"): NameObject("/Yes") #NameObject being only for checkbox, and please try "/Yes" or "/1" or "/On" to see which works
            }
        )
    
            with open(file_name, "wb") as output_stream:
                writer.write(output_stream) #save the ticked pdf file as another file named "filled-out.pdf"
```

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "C:\Users\usr\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\usr\OneDrive\Documents\Tkinter\pages_ex.py", line 381, in generate
    if Page2.f1.get() == 1: Checkbutton(file_name, 'fall1')
  File "C:\Users\usr\OneDrive\Documents\Tkinter\pages_ex.py", line 29, in Checkbutton
    if (page["/Annots"][i].get_object())['/FT']=="/Btn" and (page["/Annots"][i].get_object())['/T']==flag: #this is my filter so that I can filter checkboxes and the checkbox I want i.e. "Check Box 3"
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_base.py", line 163, in get_object
    obj = self.pdf.get_object(self)
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\_reader.py", line 1151, in get_object
    retval = read_object(self.stream, self)  # type: ignore
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_data_structures.py", line 822, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_data_structures.py", line 269, in read_from_stream
    value = read_object(stream, pdf, forced_encoding)
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_data_structures.py", line 851, in read_object
    return NumberObject.read_from_stream(stream)
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_base.py", line 299, in read_from_stream
    return NumberObject(num)
  File "C:\Users\usr\anaconda3\lib\site-packages\PyPDF2\generic\_base.py", line 274, in __new__
    val = int(value)
ValueError: invalid literal for int() with base 10: b''
```
TODO
I'm out of town already, so I cant see what version of PyPDF2 I used that works. But I tried version 2.5.0 and that works on my laptop similarly as I had working on my desktop. So, I'm just assuming it has to be something with the latest version

**Comment by pubpub-zz** [comment] 2022-08-17 06:55
@lnoah995, can you please provide the PDF file issuing the error with your code

**Comment by lnoah995** [comment] 2022-08-17 07:00
[UG_Appl.pdf](https://github.com/py-pdf/PyPDF2/files/9357187/UG_Appl.pdf)
Heres the pdf I'm using

**Comment by pubpub-zz** [comment] 2022-08-17 08:54
@lnoah995,
Your code seems to be directly extracted from your code and is not running standalone. based on the traces, I've built this code:
```
import PyPDF2
p=PyPDF2.PdfReader("c:/UG_Appl.pdf")
page = p[0]
for i in range(len(page["/Annots"])): #in order to access the "Annots" key
        print ((page["/Annots"][i].get_object())) #to find out which of the form fills are checkbox or text fill
        if True:
            page["/Annots"][i].get_object()['/FT']
            page["/Annots"][i].get_object()['/T']
            writer_annot = page["/Annots"][i].get_object()
            writer_annot.update(
            {
                PyPDF2.generic.NameObject("/V"): PyPDF2.generic.NameObject("/Yes"), #NameObject being only for checkbox, and please try "/Yes" or "/1" or "/On" to see which works
                PyPDF2.generic.NameObject("/AS"): PyPDF2.generic.NameObject("/Yes") #NameObject being only for checkbox, and please try "/Yes" or "/1" or "/On" to see which works
            }
        )
```

With this code, I've not been able to reproduce the failure. Can you provide a mode simple and fully standalone code and provide the trace in accordance for futher analysis.

Thanks

**Comment by MartinThoma** [comment] 2022-08-17 11:32
@lnoah995 Thank you for letting us know of the issue and answering our questions :pray: 

Sometimes people use another environment than they think. Could you please execute the script created by @pubpub-zz and share the output? The `"UG_Appl.pdf"` has to be in the same folder as the script.

@pubpub-zz : I've adjusted it a little bit by adding `print(PyPDF2.__version__)`. I hope that is ok :-)

**Comment by pubpub-zz** [comment] 2022-08-23 11:42
@lnoah995 any update ?

**Comment by lnoah995** [comment] 2022-08-23 21:32
@pubpub-zz Hi, my apologies for not updating. Just got back into town and had some other things to worry about. However, I did run the script above and it outputted version 2.10.2. Unfortunately, it doesn't produce the error when running the above script. Let me reduce my code somewhat because I've been going through it and don't believe what I originally posted was the issue. I'll tag you with the script though either today or tomorrow if that's fine, and whether I was able to find the problem.

**Comment by lnoah995** [comment] 2022-08-24 01:24
@pubpub-zz Hi again. So I believe I found the error. Somewhere along my program, a PDF file I had been generating and then merging, was producing an empty pdf. The dictionary was wrong and I believe that was the issue. My apologies for the mishap.

**Comment by pubpub-zz** [comment] 2022-08-24 06:00
Thx for the update

**Comment by MartinThoma** [comment] 2022-08-25 14:00
Nice! Then I can close this issue, right?

Thanks to both of you for figuring it out / coming back :-)

**Closed by MartinThoma** 2022-08-25 14:00 UTC
