### ISSUE TITLE
Getting and setting PDF version

### ISSUE THREAD

**Issue by chrysn** [py-pdf/PyPDF2#316] opened 2017-01-10 18:22 UTC
While PyPDF2 happily reads any PDF I've encountered, output files are always in PDF version 1.3. This might have adverse effects when later features are in use in pages read from other files.

In a first test, I've set a `PdfFileWriter._header = b"%PDF-1.5"` with no ill effects. Whether it actually solves my problem needs yet to be determined together with the print shop involved, but it seems their printer driver ignored transparent areas in an originally PDF 1.5 file that was output by pypdf as 1.3.

Please consider adding an option to read the PDF version from input files, and to set it on output files before they are written.

**Comment by bdheeman** [comment] 2017-10-13 18:03
Please, **consider using the highest version read from the PDF input files**, this _will be useful for the reading, manipulating and printing client software/tools_.

**Comment by MartinThoma** [comment] 2022-06-27 21:11
Getting the PDF version: https://github.com/py-pdf/PyPDF2/pull/1013

**Comment by MartinThoma** [comment] 2022-06-27 21:14
Setting the PDF version is a duplicate of #162

**Closed by MartinThoma** 2022-06-27 21:14 UTC
Labels: is-feature, soon
