### ISSUE TITLE
Stream has ended unexpectedly error on certain PDF files

### ISSUE THREAD

**Issue by LunkRat** [py-pdf/PyPDF2#99] opened 2014-05-13 15:51 UTC
We process dozens of PDF files per day in our automated script that uses PyPDF2 version 1.21 as part of its process. A few files have been failing with the error pasted below. I can provide the PDF file that is having this error, just let me know how you would like me to send it. Thanks!

``` python
PdfReadWarning: Invalid stream (index 0) within object 62 0: Stream has ended unexpectedly [pdf.py:1128]
Traceback (most recent call last):
  File "d:\scripts\mtx-coverpage\mtx-coverpage.py", line 99, in <module>
    addpage.write(outfile)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\merger.py", line 209, in write
    self.output.write(fileobj)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 277, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 365, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 341, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 365, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 341, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 350, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 365, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 341, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 379, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 341, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 370, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 1149, in getObject
    retval = self._getObjectFromStream(indirectReference)
  File "D:\bin\Python27\lib\site-packages\PyPDF2\pdf.py", line 1131, in _getObjectFromStream
    raise utils.PdfReadError("Can't read object stream: %s"%e)
PyPDF2.utils.PdfReadError: Can't read object stream: Stream has ended unexpectedly
```

**Comment by cryptid11** [comment] 2015-01-29 15:18
maybe works for PdfFileReader but not with PdfFileMerger.

I try merger = PdfFileMerger(strict = False)

and also into merger.append(PdfFileReader(open(os.path.join(files_dir, f), "rb"), strict = False)) 
but it gives the same problem as before

  File "/usr/lib/python2.7/site-packages/PyPDF2/pdf.py", line 405, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/lib/python2.7/site-packages/PyPDF2/pdf.py", line 386, in _sweepIndirectReferences
    data[key] = value
  File "/usr/lib/python2.7/site-packages/PyPDF2/generic.py", line 487, in __setitem__
    if not isinstance(key, PdfObject):
RuntimeError: maximum recursion depth exceeded in __instancecheck__


other solutions? How can I write the command inside pdf.py?

**Comment by appurwar** [comment] 2018-07-19 14:48
Try merging your PDFs by using the 'append' and 'merge' functionality of PyPDF2 instead. 

I faced the same issue and following approach worked for me - 

from PyPDF2 import PdfFileMerger

merger = PdfFileMerger()

input1 = open("file1.pdf", "rb")
input2 = open("file2.pdf", "rb")


# add the first 3 pages of first file to output
merger.append(fileobj = input1, pages = (0,3))

# insert the first page of second file into the output beginning after the second page
merger.merge(position = 2, fileobj = input2, pages = (0,1))

# Write to an output PDF document
output = open("document-output.pdf", "wb")
merger.write(output)


# Remove the 'pages' argument in 'append' and 'merge' functions to merge files instead of specific pages.

**Comment by khibma** [comment] 2018-08-09 13:45
I just started to experience this issue when calling `PdfFileReader`. I haven't changed anything in the code, maybe a windows update? None of the above suggestions to set `strict = False` seem to help. I have to go in and comment out the `file` work inside `_showwarning` and pass on the function to get anywhere.

The only difference in my case different from the above is it only happens after I've run the code once. I'm calling calling this from within ArcGIS (mapping software). I have to close the software and re-open it to get the 1st successful run. This seems to indicate that something is being held onto after the 1st run...but again, it just started happening. I realize this probably doesn't help you move towards a fix: just reporting to up the user count for this.

**Comment by reportgunner** [comment] 2019-11-11 14:54
@appurwar the error is returned no matter if append or merge is used. The problem here seems to be the format of the PDF that is being appended, so it's not PyPDF2's fault. A sensible workaround seems to reformat the PDF in some other way before passing it to PyPDF2 once this is detected.

strict=False doesn't fix this either, I came here after the error happened with strict=False on.

**Comment by MartinThoma** [comment] 2022-06-26 09:23
I'm closing this issue now as it seems to be mostly about using `strict=False` which is the current default. Let me know if you still have this issue (with a full Traceback + example code ... and a PDF if possible)

**Comment by puri-gagan** [comment] 2022-07-06 07:43
Thanks @mstamy2 @mstamy2. strict=False while reading the pdf from PdfFileReader() works great and the rewritten or merged file won't get harmed but if some workaround done on pdf file that might affect the pdf structure will case the same error though the strict=False is done. Not a problem of this package

**Comment by Eslafif** [comment] 2022-08-10 12:11
Hello
I've this error with PdfFileReader() also i'm using strict=False
any help


`Traceback (most recent call last):
  File "/New Volume/projects/Files/PDF/scrap.py", line 30, in <module>
    extracted_data=extracted_data+(pdfReader.getPage(z).extractText().splitlines())
  File "/.local/lib/python3.8/site-packages/PyPDF2/_page.py", line 1045, in extractText
    return self.extract_text(Tj_sep=Tj_sep, TJ_sep=TJ_sep)
  File "/.local/lib/python3.8/site-packages/PyPDF2/_page.py", line 968, in extract_text
    content = ContentStream(content, self.pdf)
  File "/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1088, in __init__
    self.__parseContentStream(stream)
  File "/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1119, in __parseContentStream
    operands.append(read_object(stream, None))
  File "/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1228, in read_object
    return readStringFromStream(stream)
  File "/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 382, in readStringFromStream
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly`

**Comment by MartinThoma** [comment] 2022-08-10 12:21
Which version of PyPDF2 do you use?

**Comment by Eslafif** [comment] 2022-08-10 12:45
Version 2.0.0

**Comment by pubpub-zz** [comment] 2022-08-10 13:06
@Eslafif,
can you please upgrade to latest version to confirm the error is still present. If so, can you provide the PDF file, and precise which page you are getting the issue

**Comment by Eslafif** [comment] 2022-08-10 14:56
Updated and same error exist

**Comment by pubpub-zz** [comment] 2022-08-10 14:57
> Updated and same error exist

and can you provide the pdf file and the page. without, no analysis can be done

**Comment by pubpub-zz** [comment] 2022-08-10 18:39
@Eslafif 
I've tried the following code with your file successfully.
`import PyPDF2;p=PyPDF2.PdfReader("c:/RBL.BANK.pdf");p.pages[0].extract_text()`
Can you confirm that you are getting the same results

**Comment by Eslafif** [comment] 2022-08-10 19:30
Tested and giving the same error

**Comment by pubpub-zz** [comment] 2022-08-10 19:34
Can you share the output please

**Comment by Eslafif** [comment] 2022-08-10 19:43
Traceback (most recent call last):
  File "/media/New Volume/projects/bank statement/Banks statements/test.py", line 11, in <module>
    extracted_data=pdfReader.pages[17].extract_text()
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/_page.py", line 968, in extract_text
    content = ContentStream(content, self.pdf)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1088, in __init__
    self.__parseContentStream(stream)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1119, in __parseContentStream
    operands.append(read_object(stream, None))
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1228, in read_object
    return readStringFromStream(stream)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 382, in readStringFromStream
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly

**Comment by pubpub-zz** [comment] 2022-08-10 19:46
you are not using my code and the file you've provided. Can you tell what is the result with my program please

**Comment by Eslafif** [comment] 2022-08-10 19:55
Traceback (most recent call last):
  File "/media/New Volume/projects/bank statement/Banks statements/test.py", line 7, in <module>
    p.pages[17].extract_text()
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/_page.py", line 968, in extract_text
    content = ContentStream(content, self.pdf)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1088, in __init__
    self.__parseContentStream(stream)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1119, in __parseContentStream
    operands.append(read_object(stream, None))
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 1228, in read_object
    return readStringFromStream(stream)
  File "/home/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 382, in readStringFromStream
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly

**Comment by Eslafif** [comment] 2022-08-10 19:56
this's with your code

different that the file is big so i only attached the page with the problem

**Comment by pubpub-zz** [comment] 2022-08-11 10:18
@Eslafif,
When you've extracted the page, the error in the pdf has been fixed. Can you confirm this assumption testing the code on your "small" file.

**Comment by pubpub-zz** [comment] 2022-08-21 19:26
@Eslafif,
can you confirm the fix ?

**Comment by pubpub-zz** [comment] 2022-09-03 12:15
@MartinThoma,
    I think we can close this issue

**Comment by MartinThoma** [comment] 2022-09-06 19:37
I'm closing the issue as I believe it's solved.

If anybody still has this issue with the latest PyPDF2 version, please let us know.

**Closed by MartinThoma** 2022-09-06 19:37 UTC
Labels: is-bug

**Comment by mmariani3** [comment] 2023-03-12 19:59
`## Import
from PyPDF2 import PdfReader

## Declare the PdfFileReader instance
pdf = PdfReader(open(r'Bank Statements\20230218-statements-9172-.pdf', 'rb'), strict = False)

## Create a new text file and open it in write mode
with open(r'Personal', 'w') as f:
  ## Loop through the PDF pages
    for page in pdf.pages:
        text = page.extract_text()
      ## Write to the text file
        f.write(text)`

**Comment by mmariani3** [comment] 2023-03-12 19:59
Output:
C:\Users\mmariani\Desktop\py4e\Personal>python Extract_pdf_text.py
Traceback (most recent call last):
  File "C:\Users\mmariani\Desktop\py4e\Personal\Extract_pdf_text.py", line 11, in <module>
    text = page.extract_text()
  File "C:\Users\mmariani\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_page.py", line 1851, in extract_text
    return self._extract_text(
  File "C:\Users\mmariani\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_page.py", line 1356, in _extract_text
    content = ContentStream(content, pdf, "bytes")
  File "C:\Users\mmariani\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic\_data_structures.py", line 877, in __init__
    self.__parse_content_stream(stream_bytes)
  File "C:\Users\mmariani\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic\_data_structures.py", line 929, in __parse_content_stream
    ii = self._read_inline_image(stream)
  File "C:\Users\mmariani\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic\_data_structures.py", line 970, in _read_inline_image
    raise PdfReadError("Unexpected end of stream")
PyPDF2.errors.PdfReadError: Unexpected end of stream

**Comment by pubpub-zz** [comment] 2023-03-12 20:22
@mmariani3 
you are using an old version. Please uninstall PyPDF2 and then install pypdf.
if you can still reproduce the problem, open a new issue and do not forget to provide the pdf.
if it is too private, you can send it to @MartinThoma [info@martin-thoma.de](mailto:info@martin-thoma.de)

**Comment by mmariani3** [comment] 2023-03-12 22:41
ah! Works like a charm now

**Comment by ggrantrowberry** [comment] 2023-08-09 16:33
I'm having this same problem. I have tried strict=False, as mentioned above, with no luck. Here is my code 
```
def parse_pdf(path):
    try:
        reader = PdfReader(path, strict=False)
        text = ""
        for page in reader.pages:
            text += page.extract_text() + "\n"
        return text
    except Exception as e:
        logger.warn(f"Failed to parse PDF {path}")
        raise e
```
Version: 
```
>>> pypdf.__version__
'3.15.0'
```
Errors
```
Traceback (most recent call last):
  File "/Users/grant/Projects/study_app/file-processing-server/parse.py", line 61, in <module>
    print(parse_pdf("2308.00014.pdf"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grant/Projects/study_app/file-processing-server/parse.py", line 16, in parse_pdf
    raise e
  File "/Users/grant/Projects/study_app/file-processing-server/parse.py", line 9, in parse_pdf
    reader = PdfReader(path, strict=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grant/Projects/study_app/file-processing-server/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 318, in __init__
    self.read(stream)
  File "/Users/grant/Projects/study_app/file-processing-server/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1537, in read
    self._find_eof_marker(stream)
  File "/Users/grant/Projects/study_app/file-processing-server/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1608, in _find_eof_marker
    line = read_previous_line(stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grant/Projects/study_app/file-processing-server/venv/lib/python3.11/site-packages/pypdf/_utils.py", line 266, in read_previous_line
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
pypdf.errors.PdfStreamError: Stream has ended unexpectedly
```
All of these pdfs gave me the same error. They are all from arXiv.org. 
[2308.00014.pdf](https://github.com/py-pdf/pypdf/files/12304785/2308.00014.pdf)
[2308.00013.pdf](https://github.com/py-pdf/pypdf/files/12304786/2308.00013.pdf)
[2308.00011.pdf](https://github.com/py-pdf/pypdf/files/12304787/2308.00011.pdf)
[2308.00010.pdf](https://github.com/py-pdf/pypdf/files/12304788/2308.00010.pdf)
[2308.00009.pdf](https://github.com/py-pdf/pypdf/files/12304790/2308.00009.pdf)
[2308.00001.pdf](https://github.com/py-pdf/pypdf/files/12304791/2308.00001.pdf)
[2308.00002.pdf](https://github.com/py-pdf/pypdf/files/12304793/2308.00002.pdf)
