### ISSUE TITLE
PyPDF2.utils.PdfReadError: EOF marker not found

### ISSUE THREAD

**Issue by rangat** [py-pdf/PyPDF2#442] opened 2018-07-13 17:58 UTC
PyPDF2 is not working for me on auto-generated files where the EOF marker isn't in the last 1k of the file. I understand that as part of the PDF spec it is supposed to exist that way but only searching for the last 1k does not handle all file cases correctly (appended and generated pdfs). 

This is the commit that changes it - https://github.com/mstamy2/PyPDF2/commit/f1d48827ea321d5f3cfd4ec93062f61203779312

**Comment by mdoliner-st** [comment] 2020-04-03 17:52
This issue may be a duplicate of https://github.com/mstamy2/PyPDF2/issues/177 (though your description "EOF marker isn't in the last 1k of the file") is certainly more concise. I think you're right about the behavior having changed and been made weird by https://github.com/mstamy2/PyPDF2/commit/f1d48827ea321d5f3cfd4ec93062f61203779312

**Comment by markdoliner** [comment] 2020-04-03 17:54
This issue may be a duplicate of https://github.com/mstamy2/PyPDF2/issues/177 (though your description "EOF marker isn't in the last 1k of the file") is certainly more concise. I think you're right about the behavior having changed and been made weird by https://github.com/mstamy2/PyPDF2/commit/f1d48827ea321d5f3cfd4ec93062f61203779312

**Closed** 2022-04-21 15:46 UTC
Labels: Bug, Robustness
