### ISSUE TITLE
PdfReadError: Illegal character in Name Object

### ISSUE THREAD

**Issue by slimpavlil** [py-pdf/PyPDF2#533] opened 2020-01-09 17:45 UTC
I wrote a bot that generated invoice pdf's and merges them together into one file. This is the merger script:

```python
def merger(input_files,output_path):
	pdf_writer = PdfFileWriter()

	reply = ""

	already_exists = 1
	done = 0
 
	for path in input_files:
		pdf_reader = PdfFileReader(path)
		for page in range(1):
			pdf_writer.addPage(pdf_reader.getPage(page))

	try:
		with open(output_path, 'wb') as fh:
			pdf_writer.write(fh)
	except:

		new_fname = output_path.split(".")

		while done == 0:

			str_exists = "(" + str(already_exists) + ")"

			if "y" in reply:
				done = 1
			if "n" in reply:
				return

			try:
				with open(new_fname[0] + str_exists + ".pdf", 'wb') as fh:
					pdf_writer.write(fh)
				done += 1
			except Exception as e:
				already_exists += 1
				if already_exists > 3:
					print("Problem so spajanim faktur:")
					print("    " + str(e))
					print("Pokracovat? (y/n)")
					reply = input()
```

After running I get an error saying: PdfReadError: Illegal character in Name Object
I have tried using strict=False but it didn;t work for me. The texts in the file are in Slovak Language. Any ideas on how to fix this? Thanks alot.

**Comment by MartinThoma** [comment] 2022-04-16 11:00
As I can't reproduce it like that, I'll close it for now. If you can give me a PDF + code which gives this issue with a PyPDF2 1.27.4+ version, I'll open it again

**Closed by MartinThoma** 2022-04-16 11:00 UTC
Labels: Bug, PdfFileWriter, change-requested
