### ISSUE TITLE
Filling forms with dots in field names

### ISSUE THREAD

**Issue by hchillon** [py-pdf/PyPDF2#545] opened 2020-04-21 07:05 UTC
I was having problems filling forms, but I found solution for all of them (see issue #355). Now I have found another problem (but a solution too). Let's go:

. A PDF 32000-1:2008 specification establishes (12.7.3.2), 

"The T entry in the field dictionary [...] holds a text string defining the field’s partial field name. The fully qualified field name is not explicitly defined but shall be constructed from the partial field names of the field and all of its ancestors. For a field with no parent, the partial and fully qualified names are the same. For a field that is the child of another field, the fully qualified name shall be formed by appending the child field’s partial name to the parent’s fully qualified name, separated by a PERIOD"

And PYPDF2 in some parts uses field '/T' attribute in order to identify the element and do some actions (see PdfWritter.updatePageFormFieldValues(...).

. But in the same document, different textfields may have the same 'partial field name' (and different 'fully qualified field name'. Vg: Costumer.Name and Salesman.Name.

. This kind of situations causes problems when getting data or filling data with a form, because PYPDF2 identifies textfields by means of 'partial field name'.

. I am using this trick with this kind of problem:

1.  I build a subclass of PdfWritter where there's a method for writing the 'fully qualified field name' in the '/TU' field attribute ("An alternate field name that shall be used in place of the actual field name wherever the field shall be identified in the user interface ... "). I call this method before the beginning of the updating process.

2. Update textfield methods use this attribute ('/TU') and not the ('/T') attribute.

Code:

```python
class MyPdfFileWriter(PdfFileWriter):
    
    def __init__(self):
        super().__init__()
        
    def updatePageFormCheckboxValues(self, page, fields):
 
        for j in range(0, len(page['/Annots'])):
            writer_annot = page['/Annots'][j].getObject()
            for field in fields:
                if writer_annot.get('/T') == field:
                    if fields[field] in ('/1', '/Yes'): # You choose which values use in your code
                        writer_annot.update({
                            NameObject("/V"): NameObject(fields[field]),
                            NameObject("/AS"): NameObject(fields[field])
                        })

    def updatePageFormFieldValues(self, page, fields):

        # Iterate through pages, update field values
        for j in range(0, len(page['/Annots'])):
            writer_annot = page['/Annots'][j].getObject()
            for field in fields:
                if writer_annot.get('/TU') == field:
                    writer_annot.update({
                        NameObject("/V"): TextStringObject(fields[field])
                    })

    def set_alternate_field_names(self, tree = None, retval = None, fileobj = None, basename=""):

        fieldAttributes = {"/FT" : "Field Type", "/Parent" : "Parent",
                       "/T" : "Field Name", "/TU" : "Alternate Field Name",
                       "/TM" : "Mapping Name", "/Ff" : "Field Flags",
                       "/V" : "Value", "/DV" : "Default Value"}
        if retval == None:
            retval = {}
            catalog = self._root_object
            # get the AcroForm tree
            if "/AcroForm" in catalog:
                tree = catalog["/AcroForm"]
            else:
                return None
        if tree == None:
            return retval
            
        if "/Fields" in tree:
            fields = tree["/Fields"]
            for f in fields:
                field = f.getObject()
                self.set_alternate_field_names(field, retval, fileobj)
        else:
            if basename and not basename in tree["/T"]:
                basename = basename + '.' + tree["/T"]
            else:
                basename = tree["/T"]
            if not "/Kids" in tree:
                for attr in fieldAttributes:
                    if attr in tree:
                        tree.update({NameObject('/TU'): TextStringObject(basename)})
                        # Tree is a final field
                        break
            else:
                for k in tree["/Kids"]:
                    kid = k.getObject()
                    self.set_alternate_field_names(kid, retval, fileobj, basename)
        return retval
```

Obviously, passing a dict with {text name: value} pairs to the updating text field methods WE HAVE TO USE THE FULLY QUALIFIED FIELD NAME !!. If you find the same problem with ckeckboxes names (partial name != full qualified name) you can adapt this code in order to use '/TU' attribute too.

**Comment by giorgio-pap** [comment] 2020-05-22 10:29
Hi, after reading your comment, I tried to implement this solution and I wouldn't how to make this work actually - I am not that good at scripting yet. 

This is my script:

```
from PyPDF2 import PdfFileWriter, PdfFileReader
from PyPDF2.generic import BooleanObject, NameObject, IndirectObject

def set_need_appearances_writer(writer):
    # See 12.7.2 and 7.7.2 for more information:
    # http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf
    try:
        catalog = writer._root_object
        # get the AcroForm tree and add "/NeedAppearances attribute
        if "/AcroForm" not in catalog:
            writer._root_object.update({
                NameObject("/AcroForm"): IndirectObject(len(writer._objects), 0, writer)})

        need_appearances = NameObject("/NeedAppearances")
        writer._root_object["/AcroForm"][need_appearances] = BooleanObject(True)
        return writer

    except Exception as e:
        print('set_need_appearances_writer() catch : ', repr(e))
        return writer

infile = "input.pdf"
outfile = "output.pdf"

inputStream = open(infile, "rb")
pdf_reader = PdfFileReader(inputStream, strict=False)
if "/AcroForm" in pdf_reader.trailer["/Root"]:
    pdf_reader.trailer["/Root"]["/AcroForm"].update(
        {NameObject("/NeedAppearances"): BooleanObject(True)})

pdf_writer = PdfFileWriter()
set_need_appearances_writer(pdf_writer)
if "/AcroForm" in pdf_writer._root_object:
    pdf_writer._root_object["/AcroForm"].update(
        {NameObject("/NeedAppearances"): BooleanObject(True)})

field_dictionary = {"iban1_part1": "1", "name2": "17"}

pdf_writer.addPage(pdf_reader.getPage(0))
pdf_writer.updatePageFormFieldValues(pdf_writer.getPage(0), field_dictionary)

outputStream = open(outfile, "wb")
pdf_writer.write(outputStream)

inputStream.close()
outputStream.close()
```

What part should I change according to your script?

It would be great to have your help, but please do not feel forced to do this.

**Comment by MartinThoma** [comment] 2022-04-16 11:02
I'm uncertain if this is a question of a feature request

**Comment by MartinThoma** [comment] 2022-08-06 11:59
I'm closing this as a duplicate of #355

**Closed by MartinThoma** 2022-08-06 11:59 UTC
Labels: is-bug, workflow-forms
