### ISSUE TITLE
checkbox and radio fields not getting extracted with PyPDF2

### ISSUE THREAD

**Issue by prahladyeri** [py-pdf/PyPDF2#1264] opened 2022-08-23 07:24 UTC
My project involves reading text from a bunch of PDF form files and this is the code I'm using:

    reader = PdfReader("data/test.pdf")
    cnt = len(reader.pages)
    print("reading pdf (%d pages)" % cnt)
    page = reader.pages[cnt-1]
    lines = page.extract_text().splitlines()
    print("%d lines extracted..." % len(lines))
    reader.get_fields() # returns None
    reader.get_form_text_fields() # returns None

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# Windows-10-10.0.10240-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
# 2.10.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
    reader = PdfReader("data/test.pdf")
    cnt = len(reader.pages)
    print("reading pdf (%d pages)" % cnt)
    page = reader.pages[cnt-1]
    lines = page.extract_text().splitlines()
    print("%d lines extracted..." % len(lines))
    reader.get_fields() # returns None
    reader.get_form_text_fields() # returns None
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

**Comment by pubpub-zz** [comment] 2022-08-23 07:29
@prahladyeri 
Can you provide one PDF showing the issue without no analysis will be possible

**Comment by prahladyeri** [comment] 2022-08-23 07:39
@pubpub-zz The PDF belongs to a user and contains confidential data. Is there a way I can email you the same or provide you through DM?

**Comment by pubpub-zz** [comment] 2022-08-23 08:02
can you first check this is not a duplicate of #1224 ? My first though is that the data are stored in an XFA form. Am I correct

**Comment by prahladyeri** [comment] 2022-08-23 08:10
I don't think my issue pertains to XFA, I'm not receiving any error like that other user received (`The document you are trying to load requires Adobe Reader 8 or higher...`).

Here is the metadata I'm getting for various page objects

```python
>>> from PyPDF2 import PdfReader
>>> reader = PdfReader("data/test.pdf")
>>> reader.pages[0]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_elkodgkomghfkgkjppnamlocghildcgl': IndirectObject(26, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(27, 0, 43487600)], '/Type': '/Page'}
>>> reader.pages[1]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_ognklgjjlpjcknlfbdngpgobpigkabni': IndirectObject(35, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(36, 0, 43487600)], '/Type': '/Page'}
>>> reader.pages[2]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_cchiciolobldkfmoogapocbdjjgpnkpc': IndirectObject(48, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(49, 0, 43487600)], '/Type': '/Page'}
>>> reader.pages[3]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_ilkdjemadokgkfhpahdoljefaooindpb': IndirectObject(54, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(55, 0, 43487600)], '/Type': '/Page'}
>>> reader.pages[4]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_eeoalhndfpimkigjoneckfphhbbmimde': IndirectObject(60, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(61, 0, 43487600)], '/Type': '/Page'}
>>> reader.pages[5]
{'/Parent': IndirectObject(2, 0, 43487600), '/Resources': {'/ProcSet': ['/PDF', '/Text', '/ImageC'], '/XObject': {'/ExpertPdf_ajgodeeppbhjkoeebblmndobhfgnppcd': IndirectObject(62, 0, 43487600)}}, '/MediaBox': [0, 0, 768, 1008], '/Contents': [IndirectObject(63, 0, 43487600)], '/Type': '/Page'}
>>>
```

**Comment by pubpub-zz** [comment] 2022-08-23 08:14
can you indicate what returns `"/XFA" in fo.trailer["/Root"]["/AcroForm"]`

**Comment by prahladyeri** [comment] 2022-08-23 08:19
There is no `fo` object here. When I run this on `reader` object this is what I get (Key error):

```python
>>> "/XFA" in reader.trailer["/Root"]["/AcroForm"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\localadmin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\generic\_data_structures.py", line 150, in __getitem__
    return dict.__getitem__(self, key).get_object()
KeyError: '/AcroForm'
>>>
```

**Comment by pubpub-zz** [comment] 2022-08-23 08:21
fo was my pdf document. For you try "/XFA" in reader.trailer["/Root"]["/AcroForm"]

**Comment by prahladyeri** [comment] 2022-08-23 09:47
Here it is:

```python
>>> reader.trailer["/Root"]
{'/Pages': IndirectObject(2, 0, 43487600), '/PageLayout': '/OneColumn', '/PageMode': '/UseNone', '/ViewerPreferences': IndirectObject(3, 0, 43487600), '/Type': '/Catalog'}
>>>
```

**Comment by pubpub-zz** [comment] 2022-08-23 11:41
There is no /AcroForm entry in the root which for me is for me the entry point for the forms (cf table 28 of PDF32000-1). Are you sure your document is not a printed version of a filled form ?

**Closed** 2022-08-28 13:18 UTC
