### ISSUE TITLE
Problem decrypting pdf's when the password contains special characters

### ISSUE THREAD

**Issue by rsm-gh** [py-pdf/PyPDF2#212] opened 2015-07-03 17:46 UTC
I found that pyPDF2 can not decrypt pdf's when the password contains special characters ex: "ø"

I was also surprised that most of command line gnu-linux tools can not do it either. Ex: pdftk, xpdf-utils

I first thought that this was a limitation of pdf's but Okular and Evince seems to decrypt pretty good
even if there are special characters.

**Comment by claird** [comment] 2015-10-08 17:42
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by MartinThoma** [comment] 2022-06-19 08:39
I can confirm the issue with [qpdf](https://qpdf.readthedocs.io/en/stable/cli.html#encryption-options)

```
qpdf --encrypt Søren føø 256 --force-R5 -- crazyones.pdf crazyones-256.pdf
```

And then PyPDF2 in the current `main` branch:

```python
from PyPDF2 import PdfReader
reader = PdfReader("crazyones-128.pdf", password="Søren")
```

**Comment by MartinThoma** [comment] 2022-06-19 08:39
However, I also cannot open the created document with my other document viewers. So the issue might be my terminal / qpdf

**Comment by MartinThoma** [comment] 2022-06-19 09:01
I think the issue here might be that pqdf used a different encoding. For example, I know that the letter `ü` can be represented in unicode as `u with two dots over it` and as a separate glyph. I guess you need to enter it in the same was as it was encrypted.

This seems to work fine:

```python
from PyPDF2 import PdfReader, PdfWriter

reader = PdfReader("crazyones.pdf")
writer = PdfWriter()

for page in reader.pages:
    writer.add_page(page)

writer.encrypt("Søren")
with open("crazyones-enc-new.pdf", "wb") as f:
    writer.write(f)


reader = PdfReader("crazyones-enc-new.pdf", password="Søren")
print(reader.pages[0].extract_text())
```

As this seems to be not an issue of PyPDF2, I'll close it. Please leave a comment if you still have issues with the latest version of PyPDF2.

**Closed by MartinThoma** 2022-06-19 09:01 UTC
Labels: Bug, Encryption, soon, Unicode
