### ISSUE TITLE
Reading large PDFs gives "PdfReadError: Unable to find 'endstream' marker after stream"

### ISSUE THREAD

**Issue by watt2000** [py-pdf/PyPDF2#167] opened 2015-01-04 10:28 UTC
Hi,
When I try to read some big file (>10Mo) I have a "PyPDF2.utils.PdfReadError: Unable to find 'endstream' marker after stream" error.

Here is the stack :

```
 File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 316, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 405, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 381, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 405, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 381, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 390, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 405, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 381, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 381, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 419, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 381, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 410, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1384, in getObject
    retval = readObject(self.stream, self)
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 65, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 617, in readFromStream
    raise utils.PdfReadError("Unable to find 'endstream' marker after stream at byte %s." % utils.hexStr(stream.tell()))
PyPDF2.utils.PdfReadError: Unable to find 'endstream' marker after stream at byte 0x413068.
```

How can I read big files?

**Comment by cryptid11** [comment] 2015-01-29 14:40
Same issue here, really ridiculous.

**Comment by ozax301** [comment] 2016-08-17 09:40
Did you solve this problem ?

**Comment by cryptid11** [comment] 2016-08-17 12:20
I don't resolve it, if I remind correctly! XD

**Comment by ozax301** [comment] 2016-08-17 12:38
I solved this problem.
I guess you try to write on the same pdf so it causes conflict.
If you create different pdf to write pdf, you can write big PDF.

**Comment by pinetreeps** [comment] 2018-05-31 07:54
I don't resolve it , is any other way?

**Comment by 14vv1A0516** [comment] 2018-12-10 16:56
Eventhough ,I create different PDF in different folder to write PDF , I am facing same error

**Comment by MichaelAnckaert** [comment] 2020-02-21 11:33
I'm also facing this issue in a particular case. The issue can occur with files that are not too large or are being written to a 'new' file. 

My use case, simplified:

```
merger = PdfFileMerger()
for document in documents_to_merge:
        f = io.BytesIO(document)
        merger.append(PdfFileReader(f))
        
file = io.BytesIO()
merger.write(file)
```

upon writing the merged document (```merger.write(file)```), the error occurs: Unable to find 'endstream' marker after stream at byte 0x1d5281.

This issue only occurs with some files, in my use case I suspect a bad PDF file is begin merged and can't be read for writing.

**Comment by MartinThoma** [comment] 2022-07-29 06:36
We had a lot of changes since April 2022.

I don't know how do reproduce this issue. I assume it's solved.

Please let me know if you still encounter it with the latest PyPDF2 version, then I can reopen.

**Closed by MartinThoma** 2022-07-29 06:36 UTC
Labels: PdfReader, is-robustness-issue, needs-pdf

**Comment by QLozin** [comment] 2022-10-26 07:41
> I solved this problem. I guess you try to write on the same pdf so it causes conflict. If you create different pdf to write pdf, you can write big PDF.

Thanks!!!!!!!!!
