### ISSUE TITLE
Extracting text - doubled characters in word split by space

### ISSUE THREAD

**Issue by charlesLoder** [py-pdf/PyPDF2#1321] opened 2022-09-03 17:45 UTC
When using `extractText()`, I noticed that very often when a word has two repeated characters (e.g. 'nn' or 'ss') and the next word starts with an uppercase character (though not always), the doubled characters are split by a space (e.g. 'n n' or 's s'). More often than not, 'l' is not prone to this.

I realize that "[Extracting text from a PDF can be pretty tricky](https://pypdf2.readthedocs.io/en/latest/user/extract-text.html#why-text-extraction-is-hard)," and I don't dabble in Python too often, so this may not truly be a bug.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.5-arm64-i386-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.4
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfFileReader


def extract_information(pdf_path):
    with open(pdf_path, 'rb') as f:
        pdf = PdfFileReader(f)
        number_of_pages = pdf.numPages
        for page in range(number_of_pages):
            pdfText = pdf.getPage(page).extractText()
            print(pdfText)

extract_information('./lorem_ipsum_2.pdf')
# "Donnec Pellentesque" (in pdf) prints as "Don nec Pellentesque"
# "Praessent Ac ante" (in pdf) prints as "Praes sent Ac ante"
# but, "Donnec elementum" prints as "Do nnec elementum"
```

Share here the PDF file(s) that cause the issue. The smaller 
they are, the
better. Let us know if we may add them to our tests!

Feel free to use in a test — [lorem_ipsum_2.pdf](https://github.com/py-pdf/PyPDF2/files/9483110/lorem_ipsum_2.pdf)

## Traceback

This is the complete Traceback I see:

N/A

**Comment by pubpub-zz** [comment] 2022-09-03 19:20
@charlesLoder,
this is not a bug : PDF can generate spaces by "printing" moving "cursor" between sequence of characters. this extraction is quite difficult to analyse and some spaces could be produced during text generation.
some work is identified for improvement in #1181.
this issue can be closed as duplicate

**Comment by charlesLoder** [comment] 2022-09-03 19:46
Thanks for the helpful response!

**Comment by pubpub-zz** [comment] 2022-09-03 19:49
can you then close the issue ? Thx

**Closed** 2022-09-03 19:53 UTC
