### ISSUE TITLE
PYPDF2 can extract text from some PDF files, but not the others… 

### ISSUE THREAD

**Issue by babak-khamsehi** [py-pdf/PyPDF2#437] opened 2018-06-22 15:14 UTC
I am using Python 3.6.1 on Windows 8.1 and I want to extract certain texts from a group of PDF files. To do so, I am using this code and it works fine returning the PDF as a continuous text as string variable:

```python
import PyPDF2
# creating a pdf file object
pdfFileObj = open('C:/Google Drive/Ward 29/data/ndvi.pdf', 'rb')
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj, strict=False)
# getting the number of pages in pdf file
number_of_pages =pdfReader.getNumPages()
# creating a page object
pageObj = pdfReader.getPage(0)
page_content = pageObj.extractText()
print(page_content)
# closing the pdf file object
```

However, print(page_content) does return null if I use another PDF file, “55 HARRISON GARDEN.pdf” which I actually need to extract some information from:

```python
### This code works for the ndvi file, but returns empty string for the 
harrison gdn file! I need to figure out why
import PyPDF2
# creating a pdf file object
pdfFileObj = open('C:/Google Drive/Ward 29/data/55 HARRISON GARDEN.pdf', 
'rb')
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj, strict=False)
# getting the number of pages in pdf file
number_of_pages =pdfReader.getNumPages()
# creating a page object
pageObj = pdfReader.getPage(0)
page_content = pageObj.extractText()
print(page_content)
# closing the pdf file object
pdfFileObj.close()
```

Can anyone help me figure how I can fix it to read that pdf, “55 Harrison Garden.pdf” as well?

Here are the files I mentioned: https://drive.google.com/drive/folders/1wzrPsPoeqZolsd7u0NS-I44sliFhxIpu?usp=sharing

**Comment by Yiidiir** [comment] 2018-06-26 23:10
I had the same issue, i fixed it using another python library called [slate](https://github.com/timClicks/slate)
Fortunately, i found [a fork](https://github.com/TakesxiSximada/slate3k) that works in Python 3.6.5

**Comment by hafizurcse** [comment] 2020-04-11 02:18
What I did is:

`pip install slate3k` and then 

```
import slate3k as slate

with open('my-pdf-file-name.pdf', 'rb') as f:
    extracted_text = slate.PDF(f)
print(extracted_text)```

**Comment by Yiidiir** [comment] 2020-04-11 04:27
@mstamy2 please close this.

**Comment by shivstha** [comment] 2020-05-16 08:09
import PyPDF2
# to extact all words from pdf
pdfFileObj = open('your_pdf_name.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
pdf = ''
for i in range(0, pdfReader.numPages):
    pageObj = pdfReader.getPage(i)
    page = pageObj.extractText()
    pdf = page + ' '
print(pdf)

**Comment by Akansha-SH** [comment] 2020-05-29 17:53
how to get all the pages from pdf ?

**Comment by shivstha** [comment] 2020-05-30 04:27
> how to get all the pages from pdf ?

https://github.com/mstamy2/PyPDF2/issues/437#issuecomment-629607153

**Comment by kadnan** [comment] 2020-07-12 12:40
> pip install slate3k

I ran the sample code and it returned:

_WARNING:pdfminer.layout:Too many boxes (245) to group, skipping.
WARNING:pdfminer.layout:Too many boxes (204) to group, skipping._

**Comment by UdayKumar-Ch** [comment] 2020-11-22 21:01
> I had the same issue, i fixed it using another python library called [slate](https://github.com/timClicks/slate)
> Fortunately, i found [a fork](https://github.com/TakesxiSximada/slate3k) that works in Python 3.6.5
> 
> ```
> import slate3k as slate
> 
> with open(file.pdf,'rb') as f:
>     extracted_text = slate.PDF(f)
> print(extracted_text)
> ```

Thank you @hafizurcse your solution worked well compared to pdf2reader extracting all data. thank you for sharing the solution.

**Comment by SohamDasBiswas** [comment] 2020-11-28 13:29
@UdayKumar-Ch, @Yiidiir, @hafizurcse 

Sir, Does `slate3k` can count the number of pages on a pdf?

[@Yiidiir ](https://github.com/mstamy2/PyPDF2/issues/437#issuecomment-400491342)
[@hafizurcse ](https://github.com/mstamy2/PyPDF2/issues/437#issuecomment-612300040)
[@UdayKumar-Ch ](https://github.com/mstamy2/PyPDF2/issues/437#issuecomment-731846550)

**Comment by rashmiinamdar** [comment] 2020-12-15 11:57
I tried with slate3k, but returned output as - ['\x0c']
Someone please help me

**Comment by Manjeete** [comment] 2021-02-01 11:03
> I tried with slate3k, but returned output as - ['\x0c']
> Someone please help me

same here

**Comment by Ndofi** [comment] 2021-03-15 21:55
How to extract multiple pdf files data in the same time?

**Comment by madhavmansuriya40** [comment] 2021-06-23 05:45
> I tried with slate3k, but returned output as - ['\x0c']
> Someone please help me

@rashmiinamdar @Manjeete 
image embedded PDF can be the reason for this output 
please try with the original pdf (generated from the machine)

[sample.pdf](https://github.com/mstamy2/PyPDF2/files/6699226/sample.pdf)

**Comment by pgm-master** [comment] 2021-11-16 14:47
But is it possible to extract specific text from the pdf?

**Comment by MartinThoma** [comment] 2022-04-06 20:59
Is this related to #168? Maybe even the same?

**Comment by MartinThoma** [comment] 2022-06-06 13:17
I don't know how to reproduce this issue. I guess #924 has fixed it.

I'll release `PyPDF2==2.1.0` today. Please ping me if you have this issue again/still.

**Closed by MartinThoma** 2022-06-06 13:17 UTC
Labels: Bug, Text Extraction

**Comment by ajinkyaG28** [comment] 2022-07-07 16:06
@MartinThoma I am still facing that issue(cant extract from some pdfs) with PyPDF==2.4.2.

**Comment by ajinkyaG28** [comment] 2022-07-07 20:23
@MartinThoma Cant share work related pdf, but found this example of scanned pdf online: http://solutions.weblite.ca/pdfocrx/scansmpl.pdf 
Cant extract from this pdf as well. Does PyPDF work with scanned pdfs?

**Comment by MartinThoma** [comment] 2022-07-07 21:57
No. PyPDF2 does not do ocr. This is not a bug, but simply out of scope.

**Comment by MartinThoma** [comment] 2022-07-07 21:58
But it might be worth documenting as I realize that the difference is not clear 🤔
