### ISSUE TITLE
IndexError: list index out of range after decrypting encrypted file

### ISSUE THREAD

**Issue by denis-osipov** [py-pdf/PyPDF2#327] opened 2017-02-16 10:13 UTC
After attempt to get page from encrypted file raise error 'PyPDF2.utils.PdfReadError: file has not been decrypted'.
It's ok. But after decrypting the PdfFileReader object calling pdfReader.getPage(0) raise error 'IndexError: list index out of range', although pdfReader.getNumPages() return 19.
If decript file before first call getPage() 'IndexError: list index out of range' doesn't raise.

```python
>>> pdfFileObj = open('encrypted.pdf', 'rb')
>>> pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
>>> pdfReader.getPage(0)
Traceback (most recent call last):
 ...
  File "C:\Python36\lib\site-packages\PyPDF2\pdf.py", line 1617, in getObject
    raise utils.PdfReadError("file has not been decrypted")
PyPDF2.utils.PdfReadError: file has not been decryptedd
>>> pdfReader.decrypt('rosebud')
1
>>> pageObj = pdfReader.getPage(0)
Traceback (most recent call last):
...
  File "C:\Python36\lib\site-packages\PyPDF2\pdf.py", line 1177, in getPage
    return self.flattenedPages[pageNumber]
IndexError: list index out of range
>>> pdfReader.getNumPages()
19

**Comment by CobraL0rd** [comment] 2017-07-19 00:34
I experience the same exact error. Have you figured it out?

**Comment by denis-osipov** [comment] 2017-07-19 10:14
I think so. I make PR #359 that should solve the problem. At least it works for me.

**Comment by Edely** [comment] 2017-08-27 17:36
I am having the same problem when I try to call the getPage function inside a loop.
Something like:

`numero_paginas = le_pdf.numPages

	while pagina <= numero_paginas:

		le_pdf = PyPDF2.PdfFileReader(pdf)

		texto_pagina = le_pdf.getPage(pagina).extractText()`

Raises the same error affter the first iteration.

**Comment by Topsolid1** [comment] 2018-04-02 12:18
I'm having the same issues as you.
I manually fixed it since PR #359 isn't merged yet, and I can confirm that it works for me as well.
Thanks!

**Comment by shades6057** [comment] 2018-08-27 23:46
denis-osipov, thanks, PR #359 fixed me as well.  Had to also fix it manually.  

Thanks!!

**Closed** 2022-04-16 05:47 UTC
Labels: Bug

**Comment by MartinThoma** [comment] 2022-04-16 06:10
@KeyC0de @Topsolid1 The fix was just merged and will be in the next release (some time this month). As the new maintainer, I hope to merge such fixes faster in future :crossed_fingers:
