### ISSUE TITLE
`TypeError` in `readFromStream` function

### ISSUE THREAD

**Issue by lequanvn89** [py-pdf/PyPDF2#389] opened 2018-01-18 11:03 UTC
Hi.

We got a problem with `readFromStream` function, with some PDF files we get this error `TypeError: unhashable type: 'ArrayObject'`.

Our code where we use `PyPDF2`:

```python
import io
from PyPDF2 import PdfFileReader, PdfFileWriter


def generate_signatures_images_file():
    # Read PDF file with PdfFileReader

    # Merge first page with new content

    # Write resulted page to buffer
    buffer = io.BytesIO()

    writer = PdfFileWriter()

    writer.addPage(merge_page)
    for page in other_pages:
        writer.addPage(page)
    writer.write(buffer)

    return buffer
```

Error stack trace:

```
  File "/app/api/downloads/printing.py", line 348, in generate_signatures_images_file
    writer.write(buffer)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 557, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 572, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 548, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 580, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 1675, in getObject
    retval = readObject(self.stream, self)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 582, in readFromStream
    if not data.get(key):
TypeError: unhashable type: 'ArrayObject'
```

Please, clarify it's our mistake because we pass wrong data or it's a bug in the library?

**Comment by alxpy** [comment] 2018-01-25 14:50
The problem ( `unhashable type: 'ArrayObject'` ) occurs in this place
 — https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/generic.py#L578-L582
because `key` is `ArrayObject`, but `readObject` really can return `ArrayObject` — https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/generic.py#L54-L71

I think it's problem in library.

/cc @mstamy2

**Comment by MartinThoma** [comment] 2022-06-18 12:08
Does anybody have a pdf with this issue? Does it still occur with recent versions of PyPDF2?

**Comment by MartinThoma** [comment] 2022-07-10 05:14
Without a PDF it is too hard to reproduce this issue. I close it now.

Please let me know if anybody still runs into this problem with the latest PyPDF2 version!

**Closed by MartinThoma** 2022-07-10 05:14 UTC
Labels: is-bug, needs-pdf

**Comment by yegorLitvinov** [comment] 2022-09-23 15:18
@MartinThoma @lequanvn89  I've just got the error in `pypdf2==2.10.6`, however it's not reproduced in `pypdf2==2.10.9`
