### ISSUE TITLE
Make generated PDFs on raw binary level byte-identical

### ISSUE THREAD

**Issue by ciarancourtney** [py-pdf/PyPDF2#298] opened 2016-10-26 17:08 UTC
I have a suite of tests that compare generated PDFs with corresponding reference PDFs, using basic python open() and read(), these used to work fine with PyPdf, but there are many differences with PyPDF2 

```python
generated_file = open(output_path, 'rb')
generated_data = generated_file.read()
generated.close() 

reference_file = open(reference_path, 'rb')
reference_data = reference_file.read()
reference_file.close()

if generated_data != reference_data:
        raise Exception
```

GUI PDF comparison tools like diffpdf don't detect any difference on the text or visual level, only the raw binary content is different every time

**Comment by MartinThoma** [comment] 2022-04-16 11:39
Are you saying that PyPDF2 generated files are different from PyPdf generated files? Or are you saying that if you run two times PyPDF2 that the results differ on a byte-level?

**Comment by ciarancourtney** [comment] 2022-04-17 11:25
The latter as I recall, although it was a long time ago!

> Are you saying that PyPDF2 generated files are different from PyPdf generated files? Or are you saying that if you run two times PyPDF2 that the results differ on a byte-level?

The latter as I recall, although it was a long time ago!

**Comment by MartinThoma** [comment] 2022-06-27 19:33
I cannot reproduce it and I cannot think of a reason why this should (still) happen. For this reason,  I close the issue.

I'm very much in favor of reproducibility. Let me know if this is still / becomes again an issue!

**Closed by MartinThoma** 2022-06-27 19:33 UTC
Labels: needs-discussion, is-feature
