### ISSUE TITLE
Error in extracting metadata, prompt 'XmpInformation' object has no attribute '_getText'

### ISSUE THREAD

**Issue by dzdzdzd123** [py-pdf/PyPDF2#914] opened 2022-05-27 14:03 UTC
When I use 1.27.5 and below to execute the code, the code outputs metadata information normally: such as modifyDate, but when I update to the latest version 1.28.2, the metadata information cannot be output normally: prompt
```bash
Traceback (most recent call last):
  File "C:/Users/12691/Desktop/projrct/test.py", line 8, in <module>
    print(pdfReader.xmp_metadata.xmp_modifyDate)
  File "E:\anaconda3\envs\my_env\lib\site-packages\PyPDF2\xmp.py", line 238, in get
    value = self._getText(element)
AttributeError: 'XmpInformation' object has no attribute '_getText'
```

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# TODO: Windows-10-10.0.19044-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
# TODO: 1.28.2
```

## Code

This is a minimal, complete example that shows the issue:

```python
# TODO: Your code goes here
import PyPDF2
file = 'test.pdf'
print(PyPDF2.__version__)
pdfReader = PyPDF2.PdfFileReader(open(file, 'rb'))
print(pdfReader.xmp_metadata.xmp_modifyDate)


#When I use 1.27.5 and below to execute the code, the code outputs metadata information normally: such as  modifyDate, but when I update to the latest version 1.28.2, the metadata information cannot be output normally: prompt

#AttributeError: 'XmpInformation' object has no attribute '_getText'
```

## PDF

You can use any pdf test, I have tried many, all the same error, unless downgrade to 1.27.5 and below

**Comment by MartinThoma** [comment] 2022-05-28 08:44
[PyPDF2==1.28.3](https://github.com/py-pdf/PyPDF2/releases/tag/1.28.3) fixed this issue. Thank you for reporting it :heart:

**Comment by MartinThoma** [comment] 2022-05-28 08:44
By the way: Excellent report!

**Comment by dzdzdzd123** [comment] 2022-05-29 08:54
> [PyPDF2==1.28.3](https://github.com/py-pdf/PyPDF2/releases/tag/1.28.3)修复了这个问题。谢谢你的报告❤️


I see that this problem has been closed, I don't know if you can see my reply, I updated the latest version, but it still seems not to be used, prompting the following error
```python
import PyPDF2
file = 'test.pdf'
print(PyPDF2.__version__)
pdfReader = PyPDF2.PdfFileReader(open(file, 'rb'))
print(pdfReader.xmp_metadata.xmp_modifyDate)
```

```
1.28.3
Traceback (most recent call last):
  File "C:/Users/12691/Desktop/bug.py", line 6, in <module>
    print(pdfReader.xmp_metadata.xmp_modifyDate)
  File "E:\anaconda3\envs\my_env\lib\site-packages\PyPDF2\xmp.py", line 245, in get
    value = converter(value)
TypeError: 'staticmethod' object is not callable
```

**Comment by MartinThoma** [comment] 2022-05-29 09:01
oO ... I'm sorry :see_no_evil:

**Comment by MartinThoma** [comment] 2022-05-29 09:04
I've tried to reproduce it, but I can't:

```python
import PyPDF2
file = 'Resources/commented-xmp.pdf'
print(PyPDF2.__version__)
pdfReader = PyPDF2.PdfFileReader(open(file, 'rb'))
print(pdfReader.xmp_metadata.xmp_modifyDate)
```

Results in:

```
1.28.3
None
```

Would you mind sharing the PDF that causes the issue?

**Comment by MartinThoma** [comment] 2022-05-29 09:15
I think https://github.com/py-pdf/PyPDF2/pull/921 should fix it. You can check it as follows:

```
# Get a local copy of the branch with the fix
git clone https://github.com/py-pdf/PyPDF2.git
cd PyPDF2
git checkout issue-914-unbound-static

# Use the local installation of PyPDF2 - you can change the `_version.py` e.g. to `1.28.3-issue-914` to check it worked
pip install -e . 

# Run your code
```

I would still appreciate if you could share the PDF file that causes the issue. Especially if we are allowed to add the PDF to PyPDF2 to ensure it keeps working in future.

**Comment by dzdzdzd123** [comment] 2022-05-29 10:06
> 我试图重现它，但我不能：
> 
> ```python
> import PyPDF2
> file = 'Resources/commented-xmp.pdf'
> print(PyPDF2.__version__)
> pdfReader = PyPDF2.PdfFileReader(open(file, 'rb'))
> print(pdfReader.xmp_metadata.xmp_modifyDate)
> ```
> 
> 结果是：
> 
> ```
> 1.28.3
> None
> ```
> 
> 您介意分享导致问题的 PDF 吗？
[test.pdf](https://github.com/py-pdf/PyPDF2/files/8793088/test.pdf)
Ok, sorry, I haven't found the way to upload the file before, it turns out that he is under the reply

**Comment by MartinThoma** [comment] 2022-05-29 13:14
It works for me for the current 1.28.3 version:

```
Python 3.10.2 (main, Feb  4 2022, 05:38:17) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyPDF2
>>> file = 'foo.pdf'
>>> import sys; print(sys.version)
3.10.2 (main, Feb  4 2022, 05:38:17) [GCC 9.3.0]
>>> print(PyPDF2.__version__)
1.28.3
>>> pdfReader = PyPDF2.PdfFileReader(open(file, 'rb'))
>>> print(pdfReader.xmp_metadata.xmp_modifyDate)
2022-04-09 15:22:43
```

Which Python version do you use? (`python --version`)

**Comment by MartinThoma** [comment] 2022-05-29 13:17
Uh, interesting. I can reproduce the issue with Python 3.6! Now I can check if my fix works :-)

**Comment by MartinThoma** [comment] 2022-05-29 13:46
`PyPDF2==1.28.4` is now online. Would you be so kind to check again if it works for you with the latest version of PyPDF2?

**Comment by MartinThoma** [comment] 2022-05-29 13:47
@dzdzdzd123  `PyPDF2==1.28.4` is now online. Would you be so kind to check again if it works for you with the latest version of PyPDF2?

**Comment by dzdzdzd123** [comment] 2022-05-29 14:25
> PyPDF2

Very good, my Python is Python 3.8, the latest version PyPDF2 can output results normally, I feel that it is the fastest to launch the latest version of PyPDF2, you push a new version every day

**Comment by dzdzdzd123** [comment] 2022-05-29 14:31
By the way, will this function be added later?
1. Modify PDF version information in PDF properties
2, and changes to the program information that can be opened in the security TAB
As shown below, where I use the red box, I use Adobe Acrobat
![1](https://user-images.githubusercontent.com/37803298/170874596-4d31232c-5532-4c1b-ab1e-a1b20584f3fc.jpg)
![2](https://user-images.githubusercontent.com/37803298/170874600-9ff48a28-64e8-475a-a03f-a9ffb5925a44.jpg)

**Comment by MartinThoma** [comment] 2022-05-29 15:09
I'm sorry, I can't read Chinese. If you have the characters in here as text, I can use Google Translate.

It's pretty easy to manipulate the PDF version of a file. However, the question is what the right version should be. Why do you want to change the PDF version?

> changes to the program information that can be opened in the security TAB

I'm uncertain what you mean with that. Maybe something like https://github.com/py-pdf/PyPDF2/issues/653 ?

**Comment by MartinThoma** [comment] 2022-05-29 15:10
I'm closing this issue now as it seems to be solved. I will still see your responses.

**Closed by MartinThoma** 2022-05-29 15:10 UTC
Labels: Bug
