### ISSUE TITLE
Recursion Error when outputting merged PDF File

### ISSUE THREAD

**Issue by jeffreycentex** [py-pdf/PyPDF2#268] opened 2016-06-09 16:06 UTC
I have a script that basically combines files into one PDF.  Normally it works properly, but the last few days I have had the following failure and don't know where to start:

> Uncaught exception
> Traceback (most recent call last):
>   File "C:\gitlab\payerpath\payerpath-combine.py", line 130, in <module>
>     mergedfile.write(outputfile)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\merger.py", line 230, in write
>     self.output.write(fileobj)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 482, in write
>     self._sweepIndirectReferences(externalReferenceMap, self._root)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
>     self._sweepIndirectReferences(externMap, realdata)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
>     value = self._sweepIndirectReferences(externMap, value)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
>     self._sweepIndirectReferences(externMap, realdata)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
>     value = self._sweepIndirectReferences(externMap,  value)

 ----  repeat the last 4 lines about 700 times ---

>  File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
>     value = self._sweepIndirectReferences(externMap, value)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
>     self._sweepIndirectReferences(externMap, realdata)
>   File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 552, in _sweepIndirectReferences
>     data[key] = value
>   File "C:\Anaconda\lib\site-packages\PyPDF2\generic.py", line 502, in __setitem__
>     if not isinstance(key, PdfObject):
> RuntimeError: maximum recursion depth exceeded in **instancecheck**

No other errors.

Any hidden setting that could help with this one?

**Comment by patroqueeet** [comment] 2017-05-01 18:54
+1

**Comment by MartinThoma** [comment] 2022-06-18 17:52
Thank you for reporting this issue ❤️

I cannot reproduce this issue. As the code base has charged quite a bit, I'll close this issue.

Please let me know if you still see this in the latest PyPDF2 version!

**Closed by MartinThoma** 2022-06-18 17:52 UTC
Labels: Bug, PdfFileMerger
