### ISSUE TITLE
Filled out fields are gone when convert to image

### ISSUE THREAD

**Issue by toboklee** [py-pdf/PyPDF2#546] opened 2020-04-22 21:13 UTC
Hi all,

I have an issue where all the fields that I filled out are gone after converting to image via pdf2image library.

`/NeedAppearances` attribute helped making it show up to print preview, but 
when I convert the PDF to image all fields are gone.

Not sure if it helps, but when the pdf is opened from Acrobat reader (after all fields are filled out), the file shows up as unsaved state and asks me to save it. After saving the file from Acrobat reader, all fields show up when converted to an image.

Is there an attribute that I can set to lock (or save) the field? 

Thanks in advance.

```python
 def fill(self, data_dict):
        input_stream = open(self.SOURCE, "rb")
        pdf_reader = PyPDF2.PdfFileReader(input_stream, strict=False)
        if "/AcroForm" in pdf_reader.trailer["/Root"]:
            pdf_reader.trailer["/Root"]["/AcroForm"].update(
                {NameObject("/NeedAppearances"): BooleanObject(True)})

        pdf_writer = PyPDF2.PdfFileWriter()
        self.set_need_appearances_writer(pdf_writer)
        if "/AcroForm" in pdf_writer._root_object:
            # Acro form is form field, set needs appearances to fix printing issues
            pdf_writer._root_object["/AcroForm"].update(
                {NameObject("/NeedAppearances"): BooleanObject(True)})

        pdf_writer.addPage(pdf_reader.getPage(0))
        page = pdf_writer.getPage(0)
        for j in range(0, len(page['/Annots'])):
            writer_annot = page['/Annots'][j].getObject()
            for field in data_dict:
                if writer_annot.get('/T') == field:
                    writer_annot.update({
                        NameObject("/Ff"): NumberObject(1)
                    })

        pdf_writer.updatePageFormFieldValues(page, data_dict)

        with open(self.DESTINATION, 'wb') as fh:
            pdf_writer.write(fh)

        input_stream.close()

        self.convert_to_image()
        return self.DESTINATION_IMG

    def convert_to_image(self):
        images = convert_from_path(self.DESTINATION)
        images[0].save(self.DESTINATION_IMG, 'JPEG')

    @staticmethod
    def set_need_appearances_writer(writer):
        try:
            catalog = writer._root_object
            # get the AcroForm tree and add "/NeedAppearances attribute
            if "/AcroForm" not in catalog:
                writer._root_object.update({
                    NameObject("/AcroForm"): IndirectObject(len(writer._objects), 0, writer)})

            need_appearances = NameObject("/NeedAppearances")
            writer._root_object["/AcroForm"][need_appearances] = BooleanObject(True)
        except Exception as e:
            print('set_need_appearances_writer() catch : ', repr(e))

        return writer
```

**Comment by toboklee** [comment] 2020-04-24 04:50
Still troubleshooting ... and ... 

Maybe making the fields read-only is not enough? 
Is there another annotation that could be used to actually "SAVE" the field instead of making it read only? 
```
NameObject("/Ff"): NumberObject(1)
```

**Comment by fibigerg** [comment] 2020-06-06 10:43
Same problem here...

**Comment by MartinThoma** [comment] 2022-04-23 08:25
This might have the same root cause as #355

**Comment by fintibajorge** [comment] 2022-07-08 20:04
`
PyPDF2==2.4.1
`

Hello everyone, In my case I had a similar problem, not when converting my PDF to an image, but when using different readers (Chrome, Mozilla, Brave, Adobe ...) I came accross the following issue:

On browsers like Edge, Chrome, Brave the document was shown as expected, weird behaviour happened when opening the document in Mozilla, turned out that some of the fields that I in "theory" had been set to read-only were editable, we provide documents to clients that must not be editable so, I have been researching the current writer method to fill in the form, which is the following:

```python   
def update_page_form_field_values(
        self, page: PageObject, fields: Dict[str, Any], flags: int = 0
    ) -> None:
        """
        Update the form field values for a given page from a fields dictionary.

        Copy field texts and values from fields to page.
        If the field links to a parent object, add the information to the parent.

        :param page: Page reference from PDF writer where the annotations
            and field data will be updated.
        :param fields: a Python dictionary of field names (/T) and text
            values (/V)
        :param flags: An integer (0 to 7). The first bit sets ReadOnly, the
            second bit sets Required, the third bit sets NoExport. See
            PDF Reference Table 8.70 for details.
        """
        self.set_need_appearances_writer()
        # Iterate through pages, update field values
        for j in range(len(page[PG.ANNOTS])):  # type: ignore
            writer_annot = page[PG.ANNOTS][j].get_object()  # type: ignore
            # retrieve parent field values, if present
            writer_parent_annot = {}  # fallback if it's not there
            if PG.PARENT in writer_annot:
                writer_parent_annot = writer_annot[PG.PARENT]
            for field in fields:
                if writer_annot.get(FieldDictionaryAttributes.T) == field:
                    writer_annot.update(
                        {
                            NameObject(FieldDictionaryAttributes.V): TextStringObject(
                                fields[field]
                            )
                        }
                    )
                    if flags:
                        writer_annot.update(
                            {
                                NameObject(FieldDictionaryAttributes.Ff): NumberObject(
                                    flags
                                )
                            }
                        )
                elif writer_parent_annot.get(FieldDictionaryAttributes.T) == field:
                    writer_parent_annot.update(
                        {
                            NameObject(FieldDictionaryAttributes.V): TextStringObject(
                                fields[field]
                            )
                        }
                    )
```

I realized that the fields that were parent annotations, were being skipped when setting up the annotation's flags. The solution I found was using basically the same method, just adding the flags at the Parent annotation level (see example below), that made the document being perfectly visible in Mozilla. I hope this hint serves you all and, who knows, maybe it becomes a bug fix or the first steps for its fix in the future.

```python
    @staticmethod
    def fill_pdf_form_page(page, fields_mapping, flags):
        # Iterate through pages, update field values
        for j in range(len(page[PG.ANNOTS])):  # type: ignore
            writer_annot = page[PG.ANNOTS][j].get_object()  # type: ignore
            # retrieve parent field values, if present
            writer_parent_annot = {}  # fallback if it's not there
            if PG.PARENT in writer_annot:
                writer_parent_annot = writer_annot[PG.PARENT]
            for field in fields_mapping:
                if writer_annot.get(FieldDictionaryAttributes.T) == field:
                    writer_annot.update(
                        {
                            NameObject(FieldDictionaryAttributes.V): TextStringObject(
                                fields_mapping[field]
                            )
                        }
                    )
                    if flags:
                        writer_annot.update(
                            {
                                NameObject(FieldDictionaryAttributes.Ff): NumberObject(
                                    flags
                                )
                            }
                        )
                elif writer_parent_annot.get(FieldDictionaryAttributes.T) == field:
                    writer_parent_annot.update(
                        {
                            NameObject(FieldDictionaryAttributes.V): TextStringObject(
                                fields_mapping[field]
                            ),
                            # Addding flags to parent annotation
                            NameObject(FieldDictionaryAttributes.Ff): NumberObject(
                                flags
                            ),
                        }
                    )
```

PS: Ultra weird viewers like the preview in Whatsapp or the viewer of MS Teams show the document COMPLETELY empty, I will keep on researching hoping to find something there.

**Comment by MartinThoma** [comment] 2022-08-06 11:54
I'm closing this as a duplicate of #355 . I'm pretty certain it has the same root cause.

**Closed by MartinThoma** 2022-08-06 11:54 UTC
Labels: is-bug, workflow-forms
