### ISSUE TITLE
Digitally sign PDF document

### ISSUE THREAD

**Issue by zhangwuqiao** [py-pdf/PyPDF2#653] opened 2022-02-28 10:07 UTC
Want to add the signature function of Digitally sign document.

**Comment by sgelis** [comment] 2022-05-24 12:39
Any update/roadmap on this request? We would be delighted to help with this feature, provided we could get some guidance from contributors (we are new to this codebase).

**Comment by MartinThoma** [comment] 2022-05-24 18:49
This month we had / have a lot of changes. Only today most of them were merged back to main.

What kind of advice are you looking for?

**Comment by pubpub-zz** [comment] 2022-05-24 19:59
Another project pyHanko seems to propose such feature which may not be so easy to implement after a quick look at pdf 1.7
Does it worth to implement it ?

**Comment by MartinThoma** [comment] 2022-07-09 14:10
Very good point @pubpub-zz - let's discuss this with them as well: https://github.com/MatthiasValvekens/pyHanko/discussions/127

I wouldn't be a huge fan of introducing more dependencies and it looks very much to me that it's possible / simple to just exclude digital signatures from PyPDF2 without a real drawback for users.

**Comment by MartinThoma** [comment] 2022-07-09 16:18
I gave this another thought: I like the feature, but I also don't see the need to add it directly to PyPDF2. We have a couple of other topics/bugs in PyPDF2 which we should improve and pyHanko could be used in combination with PyPDF2.

For that reason, I would close this issue as "not in 2022". If anybody still feels we need it, we can open it in 2023 again. Are there any objections?

**Comment by MartinThoma** [comment] 2022-07-09 18:40
I'm closing this as a duplicate of https://github.com/py-pdf/PyPDF2/issues/302

**Closed by MartinThoma** 2022-07-09 18:40 UTC
Labels: PdfWriter, is-feature
